apiVersion: v1
kind: Service
metadata:
  name: myapp-active-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-preview-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80

  
